Add Packet module for inter-module socket communication
notBaekjun/notBaekjunCommon pull request #2
Opened 2022-11-17 16:50 UTC by JHH20

Resolve #1 

패킷 규격은 확장성을 위해 아래와 같이 수정
- 패킷 타입: control (no body) vs data (has body)
- 패킷 헤더 옵션: 짧은 데이터를 첨부할 경우를 위해 7 byte 공간 할당
  - body를 추가로 소캣에서 읽는 수고를 줄임
- 패킷 헤더 크기를 8의 배수로 정렬
- PING 패킷을 클래스 상수로 선언

2022-11-19 20:59 UTC, Tim3s commented on packet.py
> +    def __init__(self, ptype: bytes, length: int, opts: bytes, body: str | None):
주석에서처럼 length, type, option 순으로 받도록 parameter의 순서를 바꿔주는 게 좋을 것 같습니다.

2022-11-19 21:00 UTC, Tim3s requested changes
파일명을 __init__py에서 __init__.py로 바꿔야 할 것 같습니다.

2022-11-20 04:53 UTC, JHH20 commented on packet.py
> +    def __init__(self, ptype: bytes, length: int, opts: bytes, body: str | None):
코드에서 논리적으로 보기 편하게 `type, length, body, opts` 순으로 받고 당장 안 쓰이는 `opts`는 기본값 `b""`를 갖게 하는 건 어떤가요? 그러면 대부분의 코드는 아래와 같이 됩니다.
```python
content = "some body content that is probably json string"
some_var = Packet(Packet.TYPE, len(content), content)
```

패킷 구성대로 순서대로 받으면 이런 코드를 쓰게 될 텐데 잘 안 읽힐  것 같아요.
```python
content = "some body content that is probably json string"
some_var = Packet(len(content), Packet.TYPE, b"", content)
```

2022-11-20 12:07 UTC, Tim3s commented on packet.py
> +    def __init__(self, ptype: bytes, length: int, opts: bytes, body: str | None):
괜찮은 것 같습니다.

2022-11-20 12:19 UTC, Tim3s approved these changes
LGTM

2022-11-20 12:19 UTC, merged